import React, { useState } from 'react';
import { Server, Database, Copy, Check, Terminal, ExternalLink, Shield, Cpu, Cloud, CheckCircle2, ArrowRight } from 'lucide-react';
import { Language, translations } from '../i18n';

interface CoolifyDeploymentTabProps {
  lang: Language;
}

export const CoolifyDeploymentTab: React.FC<CoolifyDeploymentTabProps> = ({ lang }) => {
  const t = translations[lang];
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const envTemplate = `# AdPlatform - Production Environment Variables for Coolify
NODE_ENV=production
PORT=3000

# Generated by Coolify PostgreSQL resource or custom database:
DATABASE_URL=postgresql://postgres:YOUR_PASSWORD@postgresql:5432/adplatform_db

# Secure random JWT secret for authentication (min 32 chars):
JWT_SECRET=adplatform_secure_jwt_production_secret_${Math.random().toString(36).substring(2, 15)}_${Math.random().toString(36).substring(2, 15)}
`;

  const coolifyCompose = `version: '3.8'

services:
  # AdPlatform Application Service
  adplatform:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://adplatform_user:adplatform_pass@adplatform_db:5432/adplatform_db
      - JWT_SECRET=\${JWT_SECRET:-change_this_to_a_random_secure_secret_key_32_chars}
    depends_on:
      adplatform_db:
        condition: service_healthy

  # Dedicated PostgreSQL 16 Service
  adplatform_db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: adplatform_db
      POSTGRES_USER: adplatform_user
      POSTGRES_PASSWORD: adplatform_pass
    volumes:
      - adplatform_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adplatform_user -d adplatform_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  adplatform_pgdata:
`;

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Header Banner */}
      <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-2">
        <div className="flex items-center gap-2 text-sky-600 dark:text-sky-400 font-bold text-xs">
          <Server className="w-4 h-4" />
          <span>Coolify VPS Deployment Guide</span>
        </div>
        <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          {t.coolifyTitle}
        </h2>
        <p className="text-xs text-slate-600 dark:text-slate-400 max-w-3xl leading-relaxed">
          {t.coolifyDesc}
        </p>
      </div>

      {/* 4 Step Deployment Workflow Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Step 1 */}
        <div className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-xl bg-sky-50 dark:bg-sky-500/20 text-sky-600 dark:text-sky-400 font-bold flex items-center justify-center text-sm">
            1
          </div>
          <h3 className="text-sm font-bold text-slate-900 dark:text-white">
            {lang === 'ar' ? '1. أنشئ قاعدة بيانات PostgreSQL' : '1. Create PostgreSQL in Coolify'}
          </h3>
          <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
            {lang === 'ar'
              ? 'فـ لوحة Coolify، اضغط New Resource > Databases > PostgreSQL ودير اسم لقاعدة البيانات.'
              : 'In Coolify dashboard, click + New Resource > Databases > PostgreSQL.'}
          </p>
        </div>

        {/* Step 2 */}
        <div className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-xl bg-indigo-50 dark:bg-indigo-500/20 text-indigo-600 dark:text-indigo-400 font-bold flex items-center justify-center text-sm">
            2
          </div>
          <h3 className="text-sm font-bold text-slate-900 dark:text-white">
            {lang === 'ar' ? '2. أضف تطبيق AdPlatform' : '2. Add AdPlatform App'}
          </h3>
          <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
            {lang === 'ar'
              ? 'اضغط New Resource > Application > Public/Private Git Repository أو Docker Compose.'
              : 'Click + New Resource > Application > Git Repository (or Docker Compose).'}
          </p>
        </div>

        {/* Step 3 */}
        <div className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-xl bg-emerald-50 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 font-bold flex items-center justify-center text-sm">
            3
          </div>
          <h3 className="text-sm font-bold text-slate-900 dark:text-white">
            {lang === 'ar' ? '3. حط متغيرات البيئة (Env)' : '3. Set Environment Variables'}
          </h3>
          <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
            {lang === 'ar'
              ? 'دخل DATABASE_URL و JWT_SECRET فـ قسم Environment Variables فـ Coolify.'
              : 'Add DATABASE_URL and JWT_SECRET to the Environment Variables panel in Coolify.'}
          </p>
        </div>

        {/* Step 4 */}
        <div className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-xl bg-amber-50 dark:bg-amber-500/20 text-amber-600 dark:text-amber-400 font-bold flex items-center justify-center text-sm">
            4
          </div>
          <h3 className="text-sm font-bold text-slate-900 dark:text-white">
            {lang === 'ar' ? '4. اضغط Deploy مبروك!' : '4. Click Deploy'}
          </h3>
          <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
            {lang === 'ar'
              ? 'السيرفر كيدير Auto-Migration للجداول تلقائياً فـ PostgreSQL بدون أي أوامر إضافية.'
              : 'Coolify will build and start the server. Auto-migration handles tables automatically.'}
          </p>
        </div>
      </div>

      {/* 2-Columns: Left Environment Variables, Right Docker Compose */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Environment Variables block */}
        <div className="p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4 text-sky-500" />
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                {lang === 'ar' ? 'متغيرات البيئة لـ Coolify (.env)' : 'Coolify Environment Variables (.env)'}
              </h3>
            </div>
            <button
              onClick={() => copyToClipboard(envTemplate, 'env_config')}
              className="text-xs text-sky-600 dark:text-sky-400 hover:text-sky-500 font-bold flex items-center gap-1"
            >
              {copiedKey === 'env_config' ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'env_config' ? t.copied : 'Copy .env'}</span>
            </button>
          </div>

          <pre className="p-4 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 text-xs font-mono text-slate-800 dark:text-slate-300 overflow-x-auto whitespace-pre-wrap select-all">
            {envTemplate}
          </pre>

          <div className="p-3 bg-sky-50 dark:bg-sky-500/10 border border-sky-200 dark:border-sky-500/20 rounded-xl text-[11px] text-sky-900 dark:text-sky-300 leading-relaxed">
            <strong>{lang === 'ar' ? 'نصيحة مهمة:' : 'Pro Tip:'}</strong>{' '}
            {lang === 'ar'
              ? 'إذا أنشأت PostgreSQL فـ نفس المشروع فـ Coolify، تقدر تستعمل الرابط الداخلي بحال: postgresql://postgres:pass@adplatform_db:5432/adplatform_db'
              : 'When creating PostgreSQL in the same Coolify project, use the internal service hostname for zero-latency network communication.'}
          </div>
        </div>

        {/* Right: Docker Compose for Coolify */}
        <div className="p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Terminal className="w-4 h-4 text-emerald-500" />
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                {lang === 'ar' ? 'ملف Docker Compose لـ Coolify' : 'Docker Compose Stack (1-Click in Coolify)'}
              </h3>
            </div>
            <button
              onClick={() => copyToClipboard(coolifyCompose, 'compose_config')}
              className="text-xs text-emerald-600 dark:text-emerald-400 hover:text-emerald-500 font-bold flex items-center gap-1"
            >
              {copiedKey === 'compose_config' ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'compose_config' ? t.copied : 'Copy docker-compose.yml'}</span>
            </button>
          </div>

          <pre className="p-4 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 text-xs font-mono text-slate-800 dark:text-slate-300 max-h-80 overflow-y-auto whitespace-pre-wrap select-all">
            {coolifyCompose}
          </pre>
        </div>
      </div>

      {/* Database Schema & Auto-Migration Details */}
      <div className="p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm space-y-3">
        <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-500" />
          <span>{lang === 'ar' ? 'مميزات قاعدة البيانات التلقائية فـ AdPlatform' : 'Automatic Database Features in AdPlatform'}</span>
        </h3>
        <ul className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs text-slate-600 dark:text-slate-300">
          <li className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <strong className="text-slate-900 dark:text-white block">Auto-Migration on Boot</strong>
            <span>All tables and indexes are created automatically when the Node.js server starts up.</span>
          </li>
          <li className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <strong className="text-slate-900 dark:text-white block">Connection Pooling (pg)</strong>
            <span>Optimized connection pooling handles thousands of concurrent ad requests seamlessly.</span>
          </li>
          <li className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <strong className="text-slate-900 dark:text-white block">SSL / TLS Support</strong>
            <span>Supports external cloud databases like Supabase, Neon, and RDS with SSL automatically enabled.</span>
          </li>
        </ul>
      </div>
    </div>
  );
};
